# Site settings
title: Gabriel Peyré's site
email: gabriel.peyre@ceremade.dauphine.fr
description: > # this means to ignore newlines until "baseurl:"
  Web site of Gabriel Peyré
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gpeyre.github.io" # the base hostname & protocol for your site
github_username:  gpeyre

# Build settings
markdown: kramdown
