# Usign the Clean Blog theme

title: Homepage of Gabriel Peyré
author: Gabriel Peyré
email: gabriel.peyre@ens.fr
description: Homepage of Gabriel Peyré
baseurl: ""
url: "http://www.gpeyre.com"
github_username:  gpeyre
twitter_username: gabrielpeyre

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]

name: Gabriel Peyré, recent works
gems:
  - jekyll-feed
  - jekyll-paginate
