# Usign the Clean Blog theme

title: Homepage of Gabriel Peyré
author: Gabriel Peyré
email: gabriel.peyre@ceremade.dauphine.fr
description: Homepage of Gabriel Peyré
baseurl: ""
url: "http://gpeyre.github.io/"
github_username:  gpeyre

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]

# bibliographic setting
scholar:
  style: apa
  locale: en

  sort_by: none
  order: ascending

#  bibliography_template: "{{reference}}"
  bibliography_template: {{reference}}

  source: ./_bibliography
  bibliography: references.bib


  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"