# Usign the Clean Blog theme

title: Homepage of Gabriel Peyré
author: Gabriel Peyré
email: gabriel.peyre@ceremade.dauphine.fr
description: Homepage of Gabriel Peyré
baseurl: ""
url: "http://gpeyre.github.io/"
github_username:  gpeyre

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]